version: "3.8"

services:
  backend:
    image: ghcr.io/team-one-tech-proga/schedule-backend:feature-docker
    # Build local
    # build:
    #   context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongodb/"
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongodb
    restart: unless-stopped
    # Disable if you a dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  mongodb:
    image: mongo:jammy
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: